Лабораторная работа 3
BMSTU-tda/IU5-Frontend-2022 pull request #2
Opened 2022-03-13 20:42 UTC by BMSTU-tda

## Товарищ, твой PR - твоя гордость!

- [ ] Убедись, что все тесты прошли успешно.
- [ ] Убедись, что поднялся vercel с твоей работой и бот написал тебе коментарий в пре со ссылкой.
- [ ] Проверь, что Pull Request таргетоирован в ТВОЙ ФОРКНУТЫЙ master
- [ ] Заполни отчет по лабораторной работе в Google форме
- [ ] Улыбнись, ведь ты приобрел новые навыки)

## Важно!

После того, как ты заполнишь отчет по лабе, мы поревьюим его, и напишем комментарии к коду, если будут вопросы.

Когда ты увидишь зеленую галочку от нас на пре, можешь смержить PR.

- [ ] Ты увидел зеленую галочку от нас на пре?

2022-03-14 12:06 UTC, antoffee requested changes
нет тестов гитхаба

2022-03-14 12:06 UTC, antoffee commented on lab2/styles.css
> +@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;700;900&family=Roboto:wght@700&display=swap');
почему тут вторая лаба?)
и когда ты ее доделаешь?)

2022-03-14 12:06 UTC, antoffee commented on lab3/2.js
> +    min = 1000000000;
так делать не очень

2022-03-16 21:10 UTC, BMSTU-tda commented on lab2/styles.css
> +@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;700;900&family=Roboto:wght@700&display=swap');
Она почти готова, к выходным догружу

2022-03-16 21:11 UTC, BMSTU-tda commented on lab2/styles.css
> +@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;700;900&family=Roboto:wght@700&display=swap');
))

2022-03-16 21:11 UTC, BMSTU-tda commented on lab3/2.js
> +    min = 1000000000;
Исправил, тесты добавил

2022-03-17 15:27 UTC, antoffee approved these changes

2022-03-17 17:58 UTC, merged